In [ ]:
# List of used libraries and models: pandas, numpy, regression, linear regression, k-nearest neighbors, support vector machine
used_libraries_and_models = [
    "pandas",
    "numpy",
    "regression",
    "linear regression",
    "k-nearest neighbors",
    "support vector machine",
]

print("List of used libraries and models:")
print(", ".join(used_libraries_and_models))

List of used libraries and models:
pandas, numpy, regression, linear regression, k-nearest neighbors, support vector machine

In [ ]:
# Anaconda environment

In [ ]:
# Import pandas library as pd
import pandas as pd

In [ ]:
# Import the California housing dataset from sklearn
from sklearn.datasets import fetch_california_housing

In [ ]:
# Load the California housing dataset
data = fetch_california_housing()

In [ ]:
# Display the loaded dataset
data

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]], shape=(20640, 8)),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,)),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33:291-297, 1997.\n'}

In [ ]:
# Show the feature data of the dataset
data.data # type: ignore

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]], shape=(20640, 8))

In [ ]:
# Show the first 10 target values
data.target[:10]

array([4.526, 3.585, 3.521, 3.413, 3.422, 2.697, 2.992, 2.414, 2.267,
       2.611])

In [ ]:
# Show the name(s) of the target variable(s)
data.target_names

['MedHouseVal']

In [ ]:
# Show the feature names of the dataset
data.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [ ]:
# Import pandas again (if not already imported)
import pandas as pd

# Create a DataFrame from the feature data with column names
df = pd.DataFrame(data.data, columns=data.feature_names)
# Add the target column to the DataFrame
df['Target'] = data.target
# Display the DataFrame
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [ ]:
# Add the target column again (if needed)
df['Target'] = data.target
# Display the DataFrame
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [ ]:
# Show only the 'HouseAge' column
df[['HouseAge']]

       HouseAge
0          41.0
1          21.0
2          52.0
3          52.0
4          52.0
...         ...
20635      25.0
20636      18.0
20637      17.0
20638      18.0
20639      16.0

[20640 rows x 1 columns]

In [ ]:
# Show the columns 'HouseAge', 'AveBedrms', and 'Target'
df[['HouseAge', 'AveBedrms', 'Target']]

       HouseAge  AveBedrms  Target
0          41.0   1.023810   4.526
1          21.0   0.971880   3.585
2          52.0   1.073446   3.521
3          52.0   1.073059   3.413
4          52.0   1.081081   3.422
...         ...        ...     ...
20635      25.0   1.133333   0.781
20636      18.0   1.315789   0.771
20637      17.0   1.120092   0.923
20638      18.0   1.171920   0.847
20639      16.0   1.162264   0.894

[20640 rows x 3 columns]

In [ ]:
# Show descriptive statistics for the DataFrame
df.describe()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704,2.068558
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532,1.153956
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000,0.149990
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000,1.196000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000,1.797000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000,2.647250
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000,5.000010

In [ ]:
# Sort the DataFrame by 'HouseAge' in ascending order
df.sort_values(by='HouseAge')

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
3130,4.8750,1.0,5.533333,1.000000,32.0,2.133333,35.08,-117.95,1.417
19536,4.2500,1.0,20.125000,2.928571,402.0,3.589286,37.65,-120.93,1.892
12286,1.6250,1.0,3.000000,1.000000,8.0,4.000000,33.86,-116.95,0.550
18972,5.2636,1.0,7.694030,1.279851,872.0,3.253731,38.23,-122.00,1.913
10391,7.8061,2.0,11.110599,1.631336,703.0,3.239631,33.58,-117.65,3.314
...,...,...,...,...,...,...,...,...,...
19516,1.3036,52.0,9.136364,1.590909,74.0,3.363636,37.64,-121.01,0.750
1671,3.6154,52.0,5.616016,1.147844,1076.0,2.209446,38.06,-122.21,1.557
15903,3.5912,52.0,4.657407,1.066667,1209.0,2.238889,37.75,-122.41,2.849
19525,1.1875,52.0,3.354430,1.120253,325.0,2.056962,37.64,-121.00,0.906
6343,0.4999,52.0,3.875000,0.562500,44.0,2.750000,34.06,-117.75,1.125

In [ ]:
# Sort the DataFrame by 'HouseAge' in descending order
df.sort_values(by='HouseAge', ascending = False)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
18881,2.3000,52.0,3.594203,1.246377,173.0,2.507246,38.10,-122.25,1.094
1671,3.6154,52.0,5.616016,1.147844,1076.0,2.209446,38.06,-122.21,1.557
19116,3.1711,52.0,5.058309,1.011662,712.0,2.075802,38.23,-122.65,2.008
19516,1.3036,52.0,9.136364,1.590909,74.0,3.363636,37.64,-121.01,0.750
16200,1.8261,52.0,4.251613,0.993548,1368.0,4.412903,37.95,-121.27,0.546
...,...,...,...,...,...,...,...,...,...
12077,6.2308,2.0,8.801008,1.373804,5964.0,3.004534,33.87,-117.64,2.579
18972,5.2636,1.0,7.694030,1.279851,872.0,3.253731,38.23,-122.00,1.913
12286,1.6250,1.0,3.000000,1.000000,8.0,4.000000,33.86,-116.95,0.550
3130,4.8750,1.0,5.533333,1.000000,32.0,2.133333,35.08,-117.95,1.417
19536,4.2500,1.0,20.125000,2.928571,402.0,3.589286,37.65,-120.93,1.892

In [ ]:
# Show the first 5 rows of the DataFrame
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [ ]:
# Show the last 5 rows of the DataFrame
df.tail()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [ ]:
# Display the entire DataFrame
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [ ]:
# Filter rows where the target value is greater than 4.5
df[df['Target'] > 4.5]

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.52600
89,1.2434,52.0,2.929412,0.917647,396.0,4.658824,37.80,-122.27,5.00001
140,6.3624,30.0,5.615385,0.730769,126.0,2.423077,37.81,-122.18,4.83300
459,1.1696,52.0,2.436000,0.944000,1349.0,5.396000,37.87,-122.25,5.00001
489,3.0417,48.0,4.690632,1.126362,1656.0,3.607843,37.86,-122.25,4.89600
...,...,...,...,...,...,...,...,...,...
20422,5.1457,35.0,6.958333,1.217593,576.0,2.666667,34.14,-118.90,5.00001
20426,10.0472,11.0,9.890756,1.159664,415.0,3.487395,34.18,-118.69,5.00001
20427,8.6499,4.0,7.236059,1.032528,5495.0,2.553439,34.19,-118.80,5.00001
20436,12.5420,10.0,9.873315,1.102426,1179.0,3.177898,34.21,-118.69,5.00001
20443,3.3438,50.0,5.342857,0.942857,130.0,3.714286,34.27,-118.85,5.00001

In [ ]:
# Filter rows where the target value is between 3 and 4
df[(df['Target']>3) & (df['Target'] < 4)]

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
103,2.5795,52.0,3.515498,1.143556,895.0,1.460033,37.81,-122.25,3.500
...,...,...,...,...,...,...,...,...,...
20502,2.9821,45.0,4.481481,0.925926,67.0,2.481481,34.33,-118.68,3.250
20503,8.2787,27.0,6.935065,1.103896,243.0,3.155844,34.33,-118.75,3.300
20504,7.3550,11.0,7.248670,0.978723,2526.0,3.359043,34.29,-118.73,3.439
20527,1.4653,7.0,3.525794,1.017857,4479.0,8.886905,38.54,-121.79,3.100
20533,4.2432,13.0,6.350569,1.053775,2553.0,2.640124,38.54,-121.67,3.265

In [ ]:
# Display the DataFrame again
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [ ]:
# Import numpy library as np
import numpy as np

In [ ]:
# Create a copy of the DataFrame
df2 = df.copy()
# Display the copied DataFrame
df2

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [ ]:
# Set some values in 'HouseAge' column to NaN (missing)
df2.loc[0,'HouseAge'] = np.nan
df2.loc[2,'HouseAge'] = np.nan
df2.loc[20638,'HouseAge'] = np.nan
df2.loc[20639,'HouseAge'] = np.nan

# Display the DataFrame with NaN values
df2

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
0,8.3252,NaN,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,NaN,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,NaN,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,NaN,5.254717,1.162264,NaN,2.616981,39.37,-121.24,0.894

In [ ]:
# Set a value in 'Population' column to NaN (missing)
df2.loc[20639,'Population'] = np.nan
# Display the DataFrame with NaN value
df2

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
0,8.3252,NaN,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,NaN,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,NaN,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,NaN,5.254717,1.162264,NaN,2.616981,39.37,-121.24,0.894

In [ ]:
# Display the DataFrame with NaN values
df2

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
0,8.3252,NaN,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,NaN,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,NaN,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,NaN,5.254717,1.162264,NaN,2.616981,39.37,-121.24,0.894

In [ ]:
# Check for missing values in the DataFrame
df2.isnull()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
0,False,True,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
20635,False,False,False,False,False,False,False,False,False
20636,False,False,False,False,False,False,False,False,False
20637,False,False,False,False,False,False,False,False,False
20638,False,True,False,False,False,False,False,False,False
20639,False,True,False,False,True,False,False,False,False

In [ ]:
# Count the number of missing values in each column
df2.isnull().sum()   # or use df2.isna().sum()

MedInc        0
HouseAge      4
AveRooms      0
AveBedrms     0
Population    1
AveOccup      0
Latitude      0
Longitude     0
Target        0
dtype: int64

In [ ]:
# Calculate the mean of the 'HouseAge' column
m = df2['HouseAge'].mean()
# Show the calculated mean
m

np.float64(28.638883504555146)

In [ ]:
# Fill missing values in the DataFrame with the mean of 'HouseAge'
df3 = df2.fillna(m)
# Display the DataFrame after filling missing values
df3

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
0,8.3252,28.638884,6.984127,1.023810,322.000000,2.555556,37.88,-122.23,4.526
1,8.3014,21.000000,6.238137,0.971880,2401.000000,2.109842,37.86,-122.22,3.585
2,7.2574,28.638884,8.288136,1.073446,496.000000,2.802260,37.85,-122.24,3.521
3,5.6431,52.000000,5.817352,1.073059,558.000000,2.547945,37.85,-122.25,3.413
4,3.8462,52.000000,6.281853,1.081081,565.000000,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.000000,5.045455,1.133333,845.000000,2.560606,39.48,-121.09,0.781
20636,2.5568,18.000000,6.114035,1.315789,356.000000,3.122807,39.49,-121.21,0.771
20637,1.7000,17.000000,5.205543,1.120092,1007.000000,2.325635,39.43,-121.22,0.923
20638,1.8672,28.638884,5.329513,1.171920,741.000000,2.123209,39.43,-121.32,0.847
20639,2.3886,28.638884,5.254717,1.162264,28.638884,2.616981,39.37,-121.24,0.894

In [ ]:
# Count the number of missing values in each column after filling
df3.isnull().sum()